apiVersion: v1
kind: Service
metadata:
  name: nginx-thx
  labels:
    app: nginx-thx
spec:
  type: NodePort
  ports:
  - port: 80          #振り分けるPodのポート
    targetPort: 30080 #外部から接続する時のポート
  selector:
    app: nginx-thx        # app: nginx-thxのラベルがあるPodに振る