##### Deployment #####
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-thx
##### ReplicaSet  #####
spec:
  selector:
    matchLabels:
      app: nginx-thx     #このラベルが付いているPodの起動数を監視する
  replicas: 2
##### Pod #####
  template:
    metadata:
      labels:
        app: nginx-thx   #これがPodにつくラベル
    spec:
      containers:
      - name: nginx-thx   #これはPodに含まれるコンテナ名
        image: nginx      #これはコンテナイメージ(Dockerhubのnginx)
        ports:
        - containerPort: 80
        # Podにマウントするボリューム
        volumeMounts:
        - mountPath: /etc/nginx        # マウント先
          readOnly: true
          name: vol-nginx-conf         # volumesにあるこの名前のボリュームをマウント
        - mountPath: /var/log/nginx
          name: vol-log
        - mountPath: /var/www
          readOnly: true
          name: vol-nginx-html-blue
      # ボリュームの定義
      volumes:
      - name: vol-nginx-conf          # ボリューム名
        configMap:                    # ConfigMapをボリュームとしますよ
          name: nginx-conf            # ConfigMap名
          items:
            - key: nginx.conf         # ConfigMap中のこのキーの値を
              path: nginx.conf        # このファイル名にして置きます
      - name: vol-log
        emptyDir: {}
      - name: nginx-html
        configMap:
          name: vol-nginx-html-blue
          items:
            - key: blue.html  
              path: index.html
